# Generated by Django 4.2.1 on 2023-05-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Студент')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('student_level_type', models.CharField(choices=[('Bachelor', 'Bakalavr'), ('Master', 'Magistr')], max_length=50, verbose_name='Тип студента')),
                ('university_name', models.CharField(max_length=255, verbose_name='Университет')),
                ('student_need_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма контракта')),
                ('student_get_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Получено для контракта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': '- Студент',
                'verbose_name_plural': '- Студенты',
            },
        ),
    ]
