# Generated by Django 4.2.1 on 2023-05-25 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsors_company_name_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_sponsors',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsors', verbose_name='Спонсор'),
            preserve_default=False,
        ),
    ]
