# Generated by Django 4.2.1 on 2023-05-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsors_company_name_and_more'),
        ('students', '0002_students_student_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_sponsors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sponsors.sponsors', verbose_name='Спонсор'),
        ),
    ]
