# Generated by Django 4.2.1 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsors_company_name_and_more'),
        ('students', '0003_alter_students_student_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_sponsors',
        ),
        migrations.AddField(
            model_name='students',
            name='student_sponsors',
            field=models.ManyToManyField(default='', to='sponsors.sponsors', verbose_name='Спонсор'),
        ),
    ]
