# Generated by Django 4.2.1 on 2023-05-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_alter_sponsors_sponsor_type'),
        ('students', '0004_remove_students_student_sponsors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_sponsors',
            field=models.ManyToManyField(blank=True, null=True, to='sponsors.sponsors', verbose_name='Спонсор'),
        ),
    ]
