# Generated by Django 4.2.1 on 2023-05-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Спонсоры')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('sponsorship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Спонсировано')),
                ('sponsorship_sent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Потрачено')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('moderation', 'Moderatsiyada'), ('approved', 'Tasdiqlangan'), ('declained', 'Bekor qilingan')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': '- Спонсор',
                'verbose_name_plural': '- Спонсоры',
            },
        ),
    ]
