# Generated by Django 4.2.1 on 2023-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsors',
            old_name='sponsorship_sent_amount',
            new_name='sponsorship_spent_amount',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd Pul'), ('transaction', "Pul o'tkazmalari")], default='cash', max_length=50),
        ),
    ]
