# Generated by Django 4.2.1 on 2023-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_rename_sponsorship_sent_amount_sponsors_sponsorship_spent_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd Pul'), ('transaction', "Pul o'tkazmalari")], default='cash', max_length=50, verbose_name='Тип оплаты'),
        ),
    ]
