# Generated by Django 4.2.1 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsors_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_type',
            field=models.CharField(choices=[('cash', 'Naqd Pul'), ('transaction', "Pul o'tkazmalari")], default='entity', max_length=100, verbose_name='Тип спонсора'),
        ),
    ]
