# Generated by Django 4.2.1 on 2023-05-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_sponsors_sponsor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='sponsor_type',
            field=models.CharField(choices=[('entity', 'Yuridik shaxs'), ('individual', 'Jismoniy shaxs')], default='entity', max_length=100, verbose_name='Тип спонсора'),
        ),
    ]
